# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  # Sequence of patterns matched against refs/tags
  push:
    tags:
      - "*" # Push events to matching v*, i.e. v1.0, v20.15.10


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Extraer nombre del tag
        run: fullTagName=${{ github.ref }} && path='refs/tags/' && a='' && tagName=${fullTagName/$path/$a} && echo $tagName && echo "##[set-output name=tagName;]$tagName"
        id: tagName
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Run tests
        run: ./gradlew test -i
        env:
          SQL_URL: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
          HIBERNATE_DIALECT: org.hibernate.dialect.H2Dialect
          SQL_DRIVER: org:h2:Driver
